import type { Project } from '../types/project';

export const mockProject: Project = {
  id: 'praxis-dr-weber',
  name: 'Praxis Dr. Weber',
  type: 'Website Redesign',
  client: 'Dr. Maria Weber',
  clientInitials: 'MW',
  startDate: '15. Feb 2026',
  targetDate: '30. Apr 2026',
  clickupListId: '',
  clickupPhaseFieldId: null,

  tasksSummary: {
    needsAttention: 3,
    inProgress: 5,
    total: 12,
  },

  tasks: [
    { id: 't1', title: 'Logo in hoher Auflösung liefern', status: 'needs-attention', stepId: 's2' },
    { id: 't2', title: 'Farbpalette bestätigen', status: 'needs-attention', stepId: 's2' },
    { id: 't3', title: 'Texte Startseite liefern', status: 'needs-attention', stepId: 's5' },
    { id: 't4', title: 'Bildmaterial sammeln', status: 'in-progress', stepId: 's5' },
    { id: 't5', title: 'Domain DNS-Einträge prüfen', status: 'in-progress', stepId: 's7' },
  ],

  teamWorkingOn: {
    task: 'Sitemap-Entwurf',
    eta: 'Donnerstag',
    lastUpdate: 'vor 2 Stunden',
  },

  updates: [
    { text: 'Scope of Work v2 hochgeladen', time: 'vor 3 Stunden', type: 'file' },
    { text: 'Team hat Projektbrief bestätigt', time: 'Gestern', type: 'status' },
    { text: 'Neue Nachricht von Mihael', time: 'Gestern', type: 'message' },
    { text: 'Kostenaufstellung hinzugefügt', time: 'vor 2 Tagen', type: 'file' },
    { text: 'Scope of Work bereit zur Prüfung', time: 'vor 2 Tagen', type: 'status' },
  ],

  chapters: [
    {
      id: 'c1',
      title: 'Konzept',
      order: 1,
      narrative: 'Wir definieren gemeinsam den Umfang und die Ziele Ihres Projekts.',
      nextNarrative: 'Als Nächstes folgt die Seitenstruktur.',
      clickupCfOptionId: null,
      steps: [
        {
          id: 's1',
          clickupTaskId: 's1',
          title: 'Projektbrief bestätigen',
          status: 'committed',
          updatedAt: '28. Feb 2026',
          taskIds: [],
          description: 'Der Projektbrief definiert Ihre Ziele, Zielgruppe und den groben Zeitplan.',
          whyItMatters: 'Er stellt sicher, dass wir Ihre Vision genau verstehen, bevor wir mit der Planung beginnen.',
          whatBecomesFixed: 'Projektziele, Zielgruppe und Hauptanforderungen werden als Grundlage festgehalten.',
          files: [
            { name: 'Projektbrief_Final.pdf', size: '840 KB', date: '28. Feb', type: 'pdf', author: 'Dr. Weber' },
            { name: 'Logo_DrWeber_Main.svg', size: '245 KB', date: '18. Feb', type: 'svg', author: 'Dr. Weber' },
            { name: 'Logo_DrWeber_White.svg', size: '198 KB', date: '18. Feb', type: 'svg', author: 'Dr. Weber' },
            { name: 'Brand_Guidelines_2024.pdf', size: '4.2 MB', date: '18. Feb', type: 'pdf', author: 'Dr. Weber' },
            { name: 'Team_Photo_Reception.jpg', size: '3.8 MB', date: '19. Feb', type: 'img', author: 'Dr. Weber' },
            { name: 'Team_Photo_Treatment.jpg', size: '4.1 MB', date: '19. Feb', type: 'img', author: 'Dr. Weber' },
            { name: 'Praxis_Exterior.jpg', size: '5.2 MB', date: '19. Feb', type: 'img', author: 'Dr. Weber' },
            { name: 'Wettbewerber_Analyse.pdf', size: '1.6 MB', date: '20. Feb', type: 'pdf', author: 'Mihael K.' },
            { name: 'Briefing_Notizen.pdf', size: '320 KB', date: '22. Feb', type: 'pdf', author: 'Mihael K.' },
          ],
          messages: [
            { author: 'Mihael K.', role: 'team', text: 'Projektbrief sieht gut aus. Ich habe ein paar Klarstellungen markiert — könnten Sie kurz drüberschauen?', time: '27. Feb · 14:20' },
            { author: 'Dr. Weber', role: 'client', text: 'Alles passt, danke!', time: '28. Feb · 09:15' },
          ],
          commentCount: 2,
        },
        {
          id: 's2',
          clickupTaskId: 's2',
          title: 'Scope of Work freigeben',
          status: 'awaiting_input',
          updatedAt: '01. Mär 2026',
          taskIds: ['t1', 't2'],
          description: 'Dieses Dokument beschreibt, was Ihre Website beinhalten wird: Seiten, Funktionen, Zeitplan und Budget.',
          whyItMatters: 'Die Freigabe bringt uns in die nächste Phase — die Strukturierung Ihrer Website.',
          whatBecomesFixed: 'Seitenumfang, Funktionsliste, Zeitrahmen und Budget werden als Arbeitsgrundlage festgelegt.',
          files: [
            { name: 'Scope_of_Work_v2.pdf', size: '1.2 MB', date: '01. Mär', type: 'pdf', author: 'Mihael K.' },
            { name: 'Scope_of_Work_v1.pdf', size: '980 KB', date: '26. Feb', type: 'pdf', author: 'Mihael K.' },
            { name: 'Kostenaufstellung.pdf', size: '340 KB', date: '01. Mär', type: 'pdf', author: 'Mihael K.' },
            { name: 'Referenz_Inspiration.jpg', size: '2.1 MB', date: '25. Feb', type: 'img', author: 'Dr. Weber' },
          ],
          messages: [
            { author: 'Mihael K.', role: 'team', text: 'Scope v2 ist fertig. Bitte schauen Sie sich besonders die Seitenstruktur und den Zeitplan an.', time: '01. Mär · 11:00' },
          ],
          commentCount: 1,
        },
      ],
    },
    {
      id: 'c2',
      title: 'Struktur',
      order: 2,
      narrative: 'Die Seitenstruktur und Navigation Ihrer Website werden festgelegt.',
      nextNarrative: 'Danach beginnt die visuelle Gestaltung.',
      clickupCfOptionId: null,
      steps: [
        {
          id: 's3',
          clickupTaskId: 's3',
          title: 'Sitemap bestätigen',
          status: 'upcoming_locked',
          updatedAt: null,
          taskIds: [],
          description: 'Die Sitemap zeigt die Seitenstruktur und Navigation Ihrer Website.',
          whyItMatters: 'Sie definiert, wie Besucher durch Ihre Website navigieren werden.',
          whatBecomesFixed: 'Seitenhierarchie und Navigationsstruktur werden als Grundlage für Design und Inhalte festgelegt.',
          files: [],
          messages: [],
          commentCount: 0,
        },
        {
          id: 's4',
          clickupTaskId: 's4',
          title: 'Wireframes freigeben',
          status: 'upcoming_locked',
          updatedAt: null,
          taskIds: [],
          description: 'Wireframes zeigen das Layout jeder Seite — wo Texte, Bilder und Funktionen platziert werden.',
          whyItMatters: 'Sie legen das Fundament für das visuelle Design.',
          whatBecomesFixed: 'Seitenlayouts und Inhaltsblöcke werden als Designgrundlage festgelegt.',
          files: [],
          messages: [],
          commentCount: 0,
        },
      ],
    },
    {
      id: 'c3',
      title: 'Design',
      order: 3,
      narrative: 'Inhalte und visuelles Design werden gemeinsam erarbeitet.',
      nextNarrative: 'Anschließend wird die Website technisch umgesetzt.',
      clickupCfOptionId: null,
      steps: [
        {
          id: 's5',
          clickupTaskId: 's5',
          title: 'Inhalte liefern',
          status: 'upcoming_locked',
          updatedAt: null,
          taskIds: ['t3', 't4'],
          description: 'Texte, Bilder und Videos für jede Seite bereitstellen.',
          whyItMatters: 'Ohne Inhalte kann das finale Design nicht erstellt werden.',
          whatBecomesFixed: 'Bereitgestellte Inhalte werden in das Design integriert.',
          files: [],
          messages: [],
          commentCount: 0,
        },
      ],
    },
    {
      id: 'c4',
      title: 'Entwicklung',
      order: 4,
      narrative: 'Ihre Website wird technisch umgesetzt und für den Launch vorbereitet.',
      nextNarrative: 'Projekt abgeschlossen — Ihre Website ist live!',
      clickupCfOptionId: null,
      steps: [
        {
          id: 's6',
          clickupTaskId: 's6',
          title: 'Design freigeben',
          status: 'upcoming_locked',
          updatedAt: null,
          taskIds: [],
          description: 'Das finale visuelle Design Ihrer Website zur Prüfung und Freigabe.',
          whyItMatters: 'Das freigegebene Design wird 1:1 als Website umgesetzt.',
          whatBecomesFixed: 'Farben, Typografie, Layout und visueller Stil werden finalisiert.',
          files: [],
          messages: [],
          commentCount: 0,
        },
        {
          id: 's7',
          clickupTaskId: 's7',
          title: 'Website live nehmen',
          status: 'upcoming_locked',
          updatedAt: null,
          taskIds: ['t5'],
          description: 'Finale Prüfung und Veröffentlichung Ihrer neuen Website.',
          whyItMatters: 'Der letzte Schritt — Ihre Website geht online.',
          whatBecomesFixed: 'Die Website wird veröffentlicht und ist für Ihre Besucher erreichbar.',
          files: [],
          messages: [],
          commentCount: 0,
        },
      ],
    },
  ],
};
